version: '3.7'

services:
  web:
    image: dailymanager
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - "../.env/.env"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - ../.:/app
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=daily_manager
      - POSTGRES_PASSWORD=daily_manager
      - POSTGRES_DB=daily_manager
    volumes:
      - ../data/postgres/data:/var/lib/postgresql/data